### ISSUE TITLE
add plugin

### ISSUE THREAD

**Issue by MistyWorld** [c-nagy/pwnagotchi-display-password-plugin#1]
To add a plugin just create a new folder containing the plugin and note the folder in config.toml and restart pwnagotchi.
example: main.custom_plugins = "/usr/local/lib/python3.7/dist-packages/pwnagotchi/plugins/new/"

**Comment by c-nagy** [comment]
Thanks MistyWorld! I updated the Readme to have proper plugin installation instructions. I appreciate it, and please feel free to continue posting improvements.
